//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace egr.am.Models
{
    using System;
    
    public partial class POMPP
    {
        public string HTML { get; private set; }
        public string PageName { get; set; }
    }
}
