//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace egr.am.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Price()
        {
            this.MSRPDiscount = 0D;
            this.ProductBaseCost = new BaseCost();
        }
    
        public System.Guid Id { get; set; }
        public string Version { get; set; }
        public string DateProduction { get; set; }
        public string DateAdded { get; set; }
        public string DateDiscontinued { get; set; }
        public string MSRP { get; set; }
        private double MSRPDiscount { get; set; }
        public System.Guid ContractId { get; set; }
        public System.Guid ProductId { get; set; }
    
        private BaseCost ProductBaseCost { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual Product Product { get; set; }
    }
}
