//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace egr.am.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOfferingMarketing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductOfferingMarketing()
        {
            this.ProductOfferingMarketingPages = new HashSet<ProductOfferingMarketingPage>();
        }
    
        public System.Guid Id { get; set; }
        public string Status { get; set; }
        public string Version { get; set; }
        public string Type { get; set; }
        public System.DateTime DateAdded { get; set; }
        public System.DateTime DateDiscontinued { get; set; }
        public System.DateTime DateLastModified { get; set; }
        public System.Guid ProductOfferingId { get; set; }
        public string ProcessOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductOfferingMarketingPage> ProductOfferingMarketingPages { get; set; }
        public virtual ProductOffering ProductOffering { get; set; }
    }
}
