//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace egr.am.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOffering
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductOffering()
        {
            this.Products = new HashSet<Product>();
            this.ProductOfferingMarketings = new HashSet<ProductOfferingMarketing>();
        }
    
        public System.Guid Id { get; set; }
        public string ProductName { get; set; }
        public System.DateTime DateAdded { get; set; }
        public System.DateTime DateLastModified { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductOfferingMarketing> ProductOfferingMarketings { get; set; }
    }
}
