//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace egr.am.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOfferingMarketingPage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductOfferingMarketingPage()
        {
            this.Media = new HashSet<Media>();
            this.Page = new POMPP();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ProductOfferingMarketingId { get; set; }
    
        public POMPP Page { get; private set; }
    
        public virtual ProductOfferingMarketing ProductOfferingMarketing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Media> Media { get; set; }
    }
}
